import { NextResponse } from "next/server";
import packageJson from "../../../../package.json";

export async function GET() {
  return NextResponse.json({
    id: "ye-notes",
    name: "Notes",
    version: packageJson.version,
    description: "Create, organize, and share notes with tags, checklists, and reminders",
    icon: "StickyNote",
    permissions: ["timeline:write", "widgets:register"],
  surfaceSchemaVersion: 1,
    surfaces: [
    {
      id: "default-notification",
      kind: "notification",
      placement: "notification-center",
      name: "Notes reminder",
      description: "Rich Notes reminder notification body",
      embedPath: "/embed/notification/default",
      permissions: ["notifications:send"],
    },
    {
      id: "app-settings",
      kind: "settings-panel",
      placement: "app-settings",
      name: "App Settings",
      description: "App-owned settings panel",
      embedPath: "/embed/settings",
      permissions: [],
    },
      {
        id: "recent-notes",
        kind: "widget",
        placement: "dashboard",
        name: "Recent Notes",
        description: "Your most recently updated notes",
        embedPath: "/embed/widget/recent-notes",
        permissions: [],
        defaultSize: { width: 25, height: 28 },
        minSize: { width: 18, height: 20 },
        maxSize: { width: 45, height: 50 },
        refreshInterval: 300,
      },
      {
        id: "quick-capture",
        kind: "widget",
        placement: "dashboard",
        name: "Quick Capture",
        description: "Quickly create a new note from your dashboard",
        embedPath: "/embed/widget/quick-capture",
        permissions: [],
        defaultSize: { width: 25, height: 12 },
        minSize: { width: 18, height: 8 },
        maxSize: { width: 40, height: 20 },
      },
      {
        id: "pinned-notes",
        kind: "widget",
        placement: "dashboard",
        name: "Pinned Notes",
        description: "Your top pinned notes at a glance",
        embedPath: "/embed/widget/pinned-notes",
        permissions: [],
        defaultSize: { width: 22, height: 25 },
        minSize: { width: 16, height: 18 },
        maxSize: { width: 40, height: 45 },
        refreshInterval: 300,
      },
      {
        id: "note-stats",
        kind: "widget",
        placement: "dashboard",
        name: "Note Stats",
        description: "Overview of your notes collection",
        embedPath: "/embed/widget/note-stats",
        permissions: [],
        defaultSize: { width: 18, height: 18 },
        minSize: { width: 14, height: 14 },
        maxSize: { width: 30, height: 30 },
        refreshInterval: 600,
      },
      {
        id: "notes-note-created",
        kind: "timeline-card",
        placement: "timeline",
        name: "Note created",
        description: "Note created",
        embedPath: "/embed/timeline/note",
        permissions: ["timeline:write"],
        triggers: ["notes-note-created"],
      },
      {
        id: "notes-note-edited",
        kind: "timeline-card",
        placement: "timeline",
        name: "Note edited",
        description: "Note edited",
        embedPath: "/embed/timeline/note",
        permissions: ["timeline:write"],
        triggers: ["notes-note-edited"],
      },
    ],
      internet: {
      hosts: [],
      proxy: [],
    },
    inter_app: {
      provides: [
        { type: "search", description: "Search user notes" },
      ],
    },
    settings: {
      schema: [
        {
          key: "editor_font_size",
          type: "select",
          label: "Editor Font Size",
          default: "16",
          options: [
            { label: "Small (14px)", value: "14" },
            { label: "Medium (16px)", value: "16" },
            { label: "Large (18px)", value: "18" },
            { label: "Extra Large (20px)", value: "20" },
          ],
        },
      ],
    },
  });
}
